name: 'dbt_project'
version: '1.0.0'
config-version: 2

# Which dbt profile to use (matches ~/.dbt/profiles.yml)
profile: 'dbt_project'

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Folders removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Ensure seeds land where your sources expect them
seeds:
  +database: ecommerce_raw
  +schema: public
  +quote_columns: true

# Default model config (applies to all models in this project)
models:
  dbt_project:
    +materialized: view
