name: 'dbt_project'
version: '1.0.0'
config-version: 2

# Which dbt profile to use (matches ~/.dbt/profiles.yml)
profile: 'dbt_project'

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
log-path: "logs"


# Ensure seeds land where your sources expect them
# ... lines 15-18

# Ensure seeds land where your sources expect them
#seeds:
  # The following is directly under seeds:
  #dbt_project:
    #+database: ecommerce_raw
    #+schema: public
    #+quote_columns: true

# Default model config (applies to all models in this project)
# ...

# Default model config (applies to all models in this project